# Generated by Django 4.2 on 2023-04-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0)),
                ('fees', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('scheduled_date', models.DateTimeField()),
                ('department', models.CharField(max_length=50)),
                ('spec_share', models.FloatField(default=0)),
                ('govt_share', models.FloatField(default=0)),
                ('hosp_amenity_share', models.FloatField(default=0)),
                ('staff_share', models.FloatField(default=0)),
                ('total_fees', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
