# Generated by Django 4.2 on 2023-04-30 05:17

import Api.models.hospital
import Api.models.user
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default=Api.models.hospital.get_default_hospital_image_path, max_length=255, null=True, upload_to=Api.models.hospital.get_hospital_image_path)),
                ('hospital_type', models.IntegerField(choices=[(0, 'CATEGORY1A'), (1, 'CATEGORY1B'), (2, 'CATEGORY2'), (3, 'CATEGORY3')], default=0)),
                ('stoppage_charges', models.IntegerField(default=0)),
                ('consumer_number_opd', models.CharField(default=12345, max_length=10)),
                ('consumer_number_ipd', models.CharField(default=12345, max_length=10)),
                ('consumer_number_opd_refund', models.CharField(default=12345, max_length=10)),
                ('consumer_number_ipd_refund', models.CharField(default=12345, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=100)),
                ('module_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('cnic', models.CharField(max_length=13, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=90, null=True)),
                ('profile_image', models.ImageField(blank=True, default=Api.models.user.get_default_profile_image_path, max_length=255, null=True, upload_to=Api.models.user.get_profile_image_path)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=60, null=True)),
                ('next_of_kin_mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=200, null=True)),
                ('relation_with_patient', models.CharField(blank=True, max_length=100, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='male', max_length=10)),
                ('phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Api.user')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Api.hospital')),
                ('roles', models.ManyToManyField(related_name='users', to='Api.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Api.user'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', to='Api.permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Api.user'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Api.user'),
        ),
    ]
